// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200414040808_InitValue")]
    partial class InitValue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Domain.Account", b =>
                {
                    b.Property<string>("NameLogin")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<Guid>("IdTeacher")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsEnable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("NameLogin")
                        .HasName("PK_Account_1");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Domain.PointTest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Ck")
                        .HasColumnName("CK")
                        .HasColumnType("REAL");

                    b.Property<double?>("Gk")
                        .HasColumnName("GK")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("IdStudent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdSubject")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Th")
                        .HasColumnName("TH")
                        .HasColumnType("REAL");

                    b.Property<double?>("Tk")
                        .HasColumnName("TK")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdStudent");

                    b.HasIndex("IdSubject");

                    b.ToTable("PointTest");
                });

            modelBuilder.Entity("Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<bool?>("Sex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Domain.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<bool?>("Sex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Domain.Teaching", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdSubject")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdTeacher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeachDay")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("IdSubject");

                    b.HasIndex("IdTeacher");

                    b.ToTable("Teaching");
                });

            modelBuilder.Entity("Domain.PointTest", b =>
                {
                    b.HasOne("Domain.Student", "IdStudentNavigation")
                        .WithMany("PointTest")
                        .HasForeignKey("IdStudent")
                        .HasConstraintName("FK_PointTest_Student");

                    b.HasOne("Domain.Subject", "IdSubjectNavigation")
                        .WithMany("PointTest")
                        .HasForeignKey("IdSubject")
                        .HasConstraintName("FK_PointTest_Subject");
                });

            modelBuilder.Entity("Domain.Teaching", b =>
                {
                    b.HasOne("Domain.Subject", "IdSubjectNavigation")
                        .WithMany("Teaching")
                        .HasForeignKey("IdSubject")
                        .HasConstraintName("FK_Teaching_Subject");

                    b.HasOne("Domain.Teacher", "IdTeacherNavigation")
                        .WithMany("Teaching")
                        .HasForeignKey("IdTeacher")
                        .HasConstraintName("FK_Teaching_Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
